services: 
    db: 
        image: dhi.io/postgres:18
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: cinema_db
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        restart: always

volumes:
    db_data: